import fs from 'node:fs';
import assert from 'node:assert/strict';
const prime=fs.readFileSync('girls-home-thumbnail-prime.js','utf8');
const evidence=fs.readFileSync('girls-evidence-parity.js','utf8');
const html=fs.readFileSync('create-trip.html','utf8');
const deferred=fs.readFileSync('girls-performance-loader.js','utf8');

for(const token of ['BATCH_SIZE=9','MAX_MEDIA=250','CONCURRENT=2','requestIdleCallback',"visibilityState==='hidden'",'saveData','slow-2g','thumbnail_path','storage_path',"cache:'force-cache'","priority:'low'",'AbortController','GTGHomeThumbnailPrime','offset+=BATCH_SIZE','transform:{width:480,height:480,resize:\'cover\',quality:64}'])assert(prime.includes(token),`missing Girls background-thumbnail contract: ${token}`);
assert(prime.includes(".eq('album','evidence').order('created_at',{ascending:false}).limit(MAX_MEDIA)"),'Girls primer must stay isolated to Evidence and work through the bounded media set');
assert(prime.includes("if(row.thumbnail_path)")&&prime.includes("storage.from('btg-evidence').createSignedUrl(row.thumbnail_path,SIGNED_SECONDS)"),'stored Girls thumbnails must be reused directly');
assert(prime.includes("createSignedUrl(row.storage_path,SIGNED_SECONDS,{transform:"),'older Girls images without stored thumbnails must use a lightweight transformed preview');
assert(prime.includes('if(token!==runToken||document.visibilityState===\'hidden\'||evidenceActive())'),'background work must yield when the app is hidden or Evidence takes foreground ownership');
assert(prime.includes("const panel=document.querySelector('[data-panel=\"evidence\"].active');if(!panel)return"),'prepared previews must only attach once Evidence is actually visible');
assert(evidence.includes('GTGHomeThumbnailPrime?.peek'),'Girls Evidence renderer must reuse previews prepared before the section opens');
assert(!html.includes('/girls-media-readiness.js?v=4')&&!html.includes('/girls-direct-photo-viewer.js?v=6'),'full-original readiness and viewer must remain off initial HTML');
const readiness=deferred.indexOf('/girls-media-readiness.js?v=4'),viewer=deferred.indexOf('/girls-direct-photo-viewer.js?v=6');
assert(readiness>0&&viewer>readiness,'Girls Evidence route must retain readiness before viewer');
assert(!html.includes('girls-home-thumbnail-prime.js'),'Girls background primer must remain deferred rather than blocking initial HTML parsing');
assert.equal((deferred.match(/girls-home-thumbnail-prime\.js\?v=2/g)||[]).length,1,'Girls background primer must have one loader owner');
assert.match(deferred,/appTheme:\[[\s\S]*girls-home-thumbnail-prime\.js\?v=2/,'Girls preview preparation must begin app-wide after the deferred runtime starts');
console.log('PASS Girls Evidence background preparation: nine-at-a-time, low-priority, input-aware and reusable');
