import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const chrome=[process.env.CHROME_BIN,process.env.CHROME_PATH,'/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/opt/google/chrome/chrome','/usr/bin/chromium','/usr/bin/chromium-browser'].filter(Boolean).find(fs.existsSync);assert(chrome,'Chrome/Chromium required');
const port=9900+Math.floor(Math.random()*90),profile=fs.mkdtempSync(path.join(os.tmpdir(),'gtg-grid-')),pagePath=path.join(os.tmpdir(),`gtg-grid-${Date.now()}.html`);fs.writeFileSync(pagePath,'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><body></body>');let stderr='';
const pageUrl=`${pathToFileURL(pagePath).href}?trip_id=t1`;
const proc=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--disable-component-update','--remote-debugging-address=127.0.0.1',`--user-data-dir=${profile}`,`--remote-debugging-port=${port}`,pageUrl],{stdio:['ignore','ignore','pipe']});proc.stderr?.on('data',d=>stderr=(stderr+String(d)).slice(-8000));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function target(){for(let i=0;i<120;i++){if(proc.exitCode!==null)throw Error(`Chrome exited before DevTools started (code ${proc.exitCode}). ${stderr}`);for(const endpoint of ['json/list','json']){try{const r=await fetch(`http://127.0.0.1:${port}/${endpoint}`);if(r.ok){const j=await r.json();const page=j.find?.(x=>x.type==='page')||j[0];if(page)return page}}catch{}}await wait(100)}throw Error(`Chrome unavailable ${stderr}`)}
function connect(url){return new Promise((resolve,reject)=>{const ws=new WebSocket(url),pending=new Map();let id=0;ws.onopen=()=>resolve({call(method,params={}){return new Promise((res,rej)=>{const n=++id;pending.set(n,{res,rej});ws.send(JSON.stringify({id:n,method,params}))})},close(){ws.close()}});ws.onerror=reject;ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.rej(Error(m.error.message)):p.res(m.result)}}})}
async function evalJs(c,expression){const r=await c.call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
try{
 const t=await target(),c=await connect(t.webSocketDebuggerUrl);await c.call('Runtime.enable');await c.call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:3,mobile:false});
 const pixel='data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==';
 const cards=Array.from({length:6},(_,i)=>`<article class="media"><img data-media-id="g${i}" src="${pixel}"><div class="media-tools"><button data-delete-media="g${i}">Delete</button></div></article>`).join('');
 await evalJs(c,`document.documentElement.style.background='#000';document.body.style.cssText='margin:0;background:#000';document.body.innerHTML='<section data-panel="evidence" style="width:calc(100% - 24px);margin:0 auto"><div class="gallery">${cards}</div></section>';window.__viewerUrlCalls=0;window.supabase={createClient:()=>{const makeQuery=(table)=>{const q={select(){return q},eq(){return q},maybeSingle:async()=>table==='media'?{data:{id:'g0',trip_id:'t1',album:'evidence',storage_path:'x/photo.jpg',file_name:'photo-0.jpg',mime_type:'image/jpeg'},error:null}:{data:{owner_id:'u1'},error:null}};return q};return{from:makeQuery,auth:{getUser:async()=>({data:{user:{id:'u1'}}})},storage:{from:()=>({createSignedUrl:async()=>{window.__viewerUrlCalls++;return{data:{signedUrl:'${pixel}'},error:null}}})}}}};`);
 await evalJs(c,fs.readFileSync(path.join(root,'girls-mobile-evidence-grid.js'),'utf8'));await wait(160);
 const result=await evalJs(c,`(()=>{const g=document.querySelector('.gtg-mobile-media-grid'),tiles=[...g.children],gs=getComputedStyle(g),gr=g.getBoundingClientRect();return{count:tiles.length,cols:gs.gridTemplateColumns.trim().split(/\\s+/).length,gap:parseFloat(gs.columnGap),gridWidth:gr.width,viewport:innerWidth,tools:document.querySelectorAll('.media-tools').length,eyeIcons:document.querySelectorAll('.gtg-grid-media-icon').length,tiles:tiles.map(t=>{const p=t.querySelector('.gtg-mobile-media-primary'),tr=t.getBoundingClientRect(),pr=p?.getBoundingClientRect(),cs=getComputedStyle(t),ps=p?getComputedStyle(p):null;return{ratio:tr.width/tr.height,radius:cs.borderRadius,childCount:t.children.length,fill:pr&&Math.abs(pr.width-tr.width)<1&&Math.abs(pr.height-tr.height)<1,fit:ps?.objectFit,mediaId:p?.dataset.mediaId||''}})}})()`);
 assert.equal(result.count,6);assert.equal(result.cols,3);assert(Math.abs(result.gap-1)<.1);assert(Math.abs(result.gridWidth-result.viewport)<1.5);assert.equal(result.tools,0);assert.equal(result.eyeIcons,0,'redundant lower-right view icon must not be rendered');
 for(const tile of result.tiles){assert(Math.abs(tile.ratio-.75)<.015);assert.equal(tile.radius,'0px');assert.equal(tile.childCount,1);assert(tile.fill);assert.equal(tile.fit,'cover');assert(tile.mediaId)}
 await evalJs(c,fs.readFileSync(path.join(root,'girls-direct-photo-viewer.js'),'utf8'));await wait(80);await evalJs(c,`document.querySelector('.gtg-mobile-media-primary').click()`);await wait(220);
 const viewer=await evalJs(c,`(()=>{const h=document.querySelector('.gtg-immersive-media-host'),s=h?.shadowRoot,stage=s?.querySelector('.stage'),media=s?.querySelector('.media'),back=s?.querySelector('.back'),top=s?.querySelector('.top'),hr=h?.getBoundingClientRect(),sr=stage?.getBoundingClientRect(),mr=media?.getBoundingClientRect(),br=back?.getBoundingClientRect(),cs=media?getComputedStyle(media):null;return{host:!!h,shadow:!!s,headers:s?.querySelectorAll('header').length||0,oldHead:!!s?.querySelector('.gtg-direct-photo-head'),text:s?.textContent||'',width:hr?.width,height:hr?.height,stageWidth:sr?.width,stageHeight:sr?.height,mediaWidth:mr?.width,mediaHeight:mr?.height,fit:cs?.objectFit,backLeft:br?.left,backTop:br?.top,topPosition:top?getComputedStyle(top).position:'',bodyPosition:getComputedStyle(document.body).position,urlCalls:window.__viewerUrlCalls,manage:!!s?.querySelector('.manage'),menuHidden:s?.querySelector('.menu')?.hidden??null}})()`);
 assert(viewer.host&&viewer.shadow);assert.equal(viewer.headers,0);assert.equal(viewer.oldHead,false);assert(!viewer.text.includes('Official Version'));assert(!viewer.text.includes('photo-0.jpg'));assert(Math.abs(viewer.width-390)<1);assert(Math.abs(viewer.height-844)<1);assert(Math.abs(viewer.stageWidth-390)<1);assert(Math.abs(viewer.stageHeight-844)<1);assert(Math.abs(viewer.mediaWidth-390)<1);assert(Math.abs(viewer.mediaHeight-844)<1);assert.equal(viewer.fit,'cover');assert.equal(viewer.topPosition,'absolute');assert(viewer.backLeft>=10&&viewer.backLeft<=14);assert(viewer.backTop>=8&&viewer.backTop<=14);assert.equal(viewer.bodyPosition,'fixed');assert.equal(viewer.urlCalls,1);assert(viewer.manage);assert.equal(viewer.menuHidden,true);
 await evalJs(c,`document.querySelector('.gtg-immersive-media-host').shadowRoot.querySelector('.back').click()`);await wait(40);const closed=await evalJs(c,`({host:!!document.querySelector('.gtg-immersive-media-host'),bodyPosition:document.body.style.position})`);assert.equal(closed.host,false);assert.equal(closed.bodyPosition,'');
 console.log('PASS Girls mobile Evidence: 3x portrait grid with no redundant view icon plus immersive full-screen viewer');c.close();
}finally{proc.kill('SIGKILL');try{fs.rmSync(profile,{recursive:true,force:true})}catch{}try{fs.rmSync(pagePath,{force:true})}catch{}}
