import fs from 'node:fs';
import assert from 'node:assert/strict';
const prime=fs.readFileSync('girls-home-thumbnail-prime.js','utf8');
const grid=fs.readFileSync('girls-mobile-evidence-grid.js','utf8');
const html=fs.readFileSync('create-trip.html','utf8');
for(const token of ['THUMB_LIMIT=30','CONCURRENT=2','requestIdleCallback','visibilityState===\'hidden\'','saveData','slow-2g','thumbnail_path','cache:\'force-cache\'','priority:\'low\'','AbortController','GTGHomeThumbnailPrime'])assert(prime.includes(token),`missing Girls home-thumbnail contract: ${token}`);
assert(prime.includes(".eq('album','evidence').order('created_at',{ascending:false}).limit(THUMB_LIMIT)"),'Girls primer must query only the first 30 Evidence rows');
assert(prime.includes("storage.from('btg-evidence').createSignedUrl(row.thumbnail_path,SIGNED_SECONDS)"),'Girls primer must sign stored thumbnails only');
assert(prime.includes('if(token!==runToken||!row?.thumbnail_path'),'Girls home primer must never fall through to originals when a stored thumbnail is absent');
assert(grid.includes('GTGHomeThumbnailPrime?.peek'),'Girls grid must be able to paint a primed thumbnail immediately');
const readiness=html.indexOf('/girls-media-readiness.js?v=2'),home=html.indexOf('/girls-home-thumbnail-prime.js?v=1'),viewer=html.indexOf('/girls-direct-photo-viewer.js?v=4');
assert(readiness>0&&home>readiness&&viewer>home,'Girls home thumbnail primer must load after readiness and before the viewer');
console.log('PASS Girls home thumbnail prime: first 30 stored thumbnails, two low-priority workers, idle/visibility/network backoff and no original decoding');
