import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath,pathToFileURL} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const chrome=[process.env.CHROME_BIN,process.env.CHROME_PATH,'/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/opt/google/chrome/chrome','/usr/bin/chromium','/usr/bin/chromium-browser'].filter(Boolean).find(fs.existsSync);
assert(chrome,'Chrome/Chromium required');
const port=10220+Math.floor(Math.random()*80),profile=fs.mkdtempSync(path.join(os.tmpdir(),'gtg-overview-owner-')),pagePath=path.join(os.tmpdir(),`gtg-overview-owner-${Date.now()}.html`);
fs.writeFileSync(pagePath,`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>${fs.readFileSync(path.join(root,'girls-app.css'),'utf8')}</style><body><div id="app"></div><div id="drawerRoot" class="drawer-wrap"></div><div id="modalRoot" class="modal-wrap"></div><div id="toast" class="toast"></div></body>`);
let stderr='';
const proc=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--disable-component-update','--disable-extensions','--no-first-run','--no-default-browser-check','--remote-debugging-address=127.0.0.1',`--user-data-dir=${profile}`,`--remote-debugging-port=${port}`,`${pathToFileURL(pagePath).href}?trip_id=t1&action=overview`],{stdio:['ignore','ignore','pipe']});
proc.stderr?.on('data',d=>stderr=(stderr+String(d)).slice(-8000));
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function target(){for(let i=0;i<600;i++){if(proc.exitCode!==null)throw Error(`Chrome exited before DevTools started (code ${proc.exitCode}). ${stderr}`);try{const r=await fetch(`http://127.0.0.1:${port}/json`);if(r.ok){const pages=await r.json(),page=pages.find(x=>x.type==='page')||pages[0];if(page)return page}}catch{}await wait(100)}throw Error(`Chrome unavailable after 60s. ${stderr}`)}
function connect(url){return new Promise((resolve,reject)=>{const ws=new WebSocket(url),pending=new Map();let id=0;ws.onopen=()=>resolve({call(method,params={}){return new Promise((res,rej)=>{const n=++id;pending.set(n,{res,rej});ws.send(JSON.stringify({id:n,method,params}))})},close(){ws.close()}});ws.onerror=reject;ws.onmessage=event=>{const msg=JSON.parse(event.data);if(msg.id&&pending.has(msg.id)){const p=pending.get(msg.id);pending.delete(msg.id);msg.error?p.rej(Error(msg.error.message)):p.res(msg.result.value??msg.result)}}})}
async function evaluate(client,expression){const r=await client.call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}

const shell=mode=>`<main class="dashboard" data-home-composition="${mode}"><div class="shell"><div class="stat-row"><button class="stat" data-tab="plan">Plan</button><button class="stat" data-tab="money">Money</button><button class="stat" data-tab="evidence">Evidence</button><button class="stat" data-tab="group">Group</button></div><section class="panel active" data-panel="overview"><div class="section-head"><div><h2>Overview</h2></div></div><div class="overview-grid"><div class="card">Core overview</div></div></section><section class="panel" data-panel="plan"></section><section class="panel" data-panel="money"></section><section class="panel" data-panel="evidence"><div class="section-head"><div><h2>Evidence</h2></div></div></section><section class="panel" data-panel="group"></section></div></main><nav class="dock"><button data-tab="overview" class="active">Home</button><button data-tab="plan">Plan</button><button data-tab="money">Money</button><button data-tab="evidence">Evidence</button><button data-tab="group">Group</button></nav>`;

try{
 const page=await target(),client=await connect(page.webSocketDebuggerUrl);await client.call('Runtime.enable');await client.call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:3,mobile:true,screenWidth:390,screenHeight:844});
 await evaluate(client,`window.__rows={trips:[{id:'t1',name:'Test 1b',destination:'Germany',start_date:'2026-09-28',end_date:'2026-09-30',owner_id:'u1',product_key:'girls'}],trip_members:[{id:'m1',name:'Owner',user_id:'u1',role:'organiser',status:'confirmed',passport_confirmed:false}],bookings:[],documents:[],expenses:[],expense_participants:[],payment_requests:[],payment_request_participants:[],trip_entitlements:[{entitlement:'full_trip',active:true}],communication_settings:[],trip_messages:[],media:Array.from({length:19},(_,i)=>({id:'p'+i,album:'evidence',mime_type:'image/jpeg',created_at:new Date().toISOString(),created_by:'u1'}))};window.supabase={createClient:()=>{function query(table){const result=()=>({data:window.__rows[table]||[],error:null,count:table==='media'?(window.__rows.media||[]).length:null});const q={select(){return q},eq(){return q},like(){return q},in(){return q},order(){return q},limit(){return Promise.resolve(result())},single(){const r=result();return Promise.resolve({data:r.data[0]||null,error:null})},maybeSingle(){const r=result();return Promise.resolve({data:r.data[0]||null,error:null})},insert(){return Promise.resolve({data:null,error:null})},upsert(){return Promise.resolve({data:null,error:null})},then(resolve,reject){return Promise.resolve(result()).then(resolve,reject)}};return q}return{from:query,auth:{getUser:async()=>({data:{user:{id:'u1'}}})}}}};document.getElementById('app').innerHTML=${JSON.stringify(shell('full'))};`);
 await evaluate(client,fs.readFileSync(path.join(root,'girls-product-parity.js'),'utf8'));
 await wait(350);
 const full=await evaluate(client,`(()=>{const panel=document.querySelector('[data-panel="overview"]'),block=document.querySelector('[data-parity-block="overview"]'),head=panel?.querySelector(':scope > .section-head');return{exists:!!block,inOverview:!!(panel&&block&&panel.contains(block)),afterHead:head?.nextElementSibling===block,outside:document.querySelectorAll('.shell > [data-parity-block="overview"],.dashboard > [data-parity-block="overview"]').length}})()`);
 assert.deepEqual(full,{exists:true,inOverview:true,afterHead:true,outside:0},'Full overview parity content must be owned by the Overview panel');
 const hiddenImmediately=await evaluate(client,`(()=>{const overview=document.querySelector('[data-panel="overview"]'),evidence=document.querySelector('[data-panel="evidence"]'),home=document.querySelector('.dock [data-tab="overview"]'),ev=document.querySelector('.dock [data-tab="evidence"]'),block=document.querySelector('[data-parity-block="overview"]');overview.classList.remove('active');evidence.classList.add('active');home.classList.remove('active');ev.classList.add('active');return block.getClientRects().length===0})()`);
 assert.equal(hiddenImmediately,true,'Full Home parity content must disappear synchronously when Evidence becomes active');

 await evaluate(client,`window.__rows.trip_entitlements=[];history.replaceState({},'',location.pathname+'?trip_id=t1&action=overview');document.getElementById('app').innerHTML=${JSON.stringify(shell('free'))};window.dispatchEvent(new PopStateEvent('popstate'));`);
 await wait(220);
 const free=await evaluate(client,`(()=>{const panel=document.querySelector('[data-panel="overview"]'),block=document.querySelector('[data-parity-block="overview"]'),stats=document.querySelector('.stat-row');return{exists:!!block,inOverview:!!(panel&&block&&panel.contains(block)),afterStats:stats?.nextElementSibling===block}})()`);
 assert.deepEqual(free,{exists:true,inOverview:false,afterStats:true},'Free Home parity placement must remain unchanged');
 console.log('PASS Girls overview ownership: Full is panel-owned and hides immediately; Free placement unchanged');client.close();
}finally{proc.kill('SIGKILL');try{fs.rmSync(profile,{recursive:true,force:true})}catch{}try{fs.rmSync(pagePath,{force:true})}catch{}}
