import fs from 'node:fs';
import assert from 'node:assert/strict';
const prime=fs.readFileSync('girls-home-thumbnail-prime.js','utf8');
const grid=fs.readFileSync('girls-mobile-evidence-grid.js','utf8');
const html=fs.readFileSync('create-trip.html','utf8');
const deferred=fs.readFileSync('girls-performance-loader.js','utf8');
for(const token of ['THUMB_LIMIT=30','CONCURRENT=2','requestIdleCallback','visibilityState===\'hidden\'','saveData','slow-2g','thumbnail_path','cache:\'force-cache\'','priority:\'low\'','AbortController','GTGHomeThumbnailPrime','createSignedUrls','[data-panel="evidence"].active'])assert(prime.includes(token),`missing Girls home-thumbnail contract: ${token}`);
assert(prime.includes(".eq('album','evidence').order('created_at',{ascending:false}).limit(THUMB_LIMIT)"),'Girls primer must query only the first 30 Evidence rows');
assert(prime.includes("storage.from('btg-evidence').createSignedUrls(rows.map(row=>row.thumbnail_path),SIGNED_SECONDS)"),'Girls primer must batch-sign stored thumbnails only');
assert(prime.includes('if(token!==runToken||!item?.row?.thumbnail_path'),'Girls home primer must never fall through to originals when a stored thumbnail is absent');
assert(prime.includes("const panel=document.querySelector('[data-panel=\"evidence\"].active');if(!panel)return"),'Girls primer must not attach/decode cached thumbnails while Evidence is hidden');
const peek=grid.indexOf('GTGHomeThumbnailPrime?.peek'),ready=grid.indexOf("if(card.dataset.gtgMobileGridReady==='1')return");
assert(peek>=0&&ready>peek,'Girls grid must apply a primed thumbnail even when the hidden grid was normalised earlier');
const readiness=html.indexOf('/girls-media-readiness.js?v=2'),viewer=html.indexOf('/girls-direct-photo-viewer.js?v=4');
assert(readiness>0&&viewer>readiness,'Girls readiness and viewer must remain immediate and correctly ordered');
assert(!html.includes('defer src="/girls-home-thumbnail-prime.js?v=1"'),'Girls home thumbnail primer must not be a direct startup script');
assert(deferred.includes('/girls-home-thumbnail-prime.js?v=1'),'Girls deferred loader must retain the home thumbnail primer');
assert(deferred.includes('requestIdleCallback')&&deferred.includes('afterDashboard')&&deferred.includes('6000'),'Girls home thumbnail primer must wait for the dashboard, then a long post-paint idle window');
console.log('PASS Girls home thumbnail prime: first 30 stored thumbnails, batch signing, two low-priority workers and delayed post-paint startup');
