import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const loader=fs.readFileSync(path.join(root,'girls-performance-loader.js'),'utf8');
const gridCss=fs.readFileSync(path.join(root,'girls-evidence-core-grid.css'),'utf8');
const cssLiteral=JSON.stringify(gridCss);
assert.doesNotMatch(loader,/girls-mobile-evidence-grid\.js/,'legacy mobile Evidence DOM rewriter must not load');
assert.match(gridCss,/data-home-composition="full"/,'mobile Evidence grid CSS must be Full-only');
const chrome=[process.env.CHROME_BIN,process.env.CHROME_PATH,'/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/opt/google/chrome/chrome','/usr/bin/chromium','/usr/bin/chromium-browser'].filter(Boolean).find(fs.existsSync);assert(chrome,'Chrome/Chromium required');
const port=9900+Math.floor(Math.random()*90),profile=fs.mkdtempSync(path.join(os.tmpdir(),'gtg-grid-'));const fixture='<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><body></body>';let stderr='';
const proc=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--disable-component-update','--disable-extensions','--no-first-run','--no-default-browser-check','--remote-debugging-address=127.0.0.1',`--user-data-dir=${profile}`,`--remote-debugging-port=${port}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
proc.stderr?.on('data',d=>stderr=(stderr+String(d)).slice(-8000));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function target(){for(let i=0600;i++){if(proc.exitCode!==null)throw Error(`Chrome exited before DevTools started (code ${proc.exitCode}). ${stderr}`);for(const endpoint of ['json/list','json']){try{const r=await fetch(`http://127.0.0.1:${port}/${endpoint}`);if(r.ok){const j=await r.json();const page=j.find?.(x=>x.type==='page')||j[0];if(page)return page}}catch{}}await wait(100)}throw Error(`Chrome unavailable after 60s ${stderr}`)}
function connect(url){return new Promise((resolve,reject)=>{const ws=new WebSocket(url),pending=new Map();let id=0;ws.onopen=()=>resolve({call(method,params={}){return new Promise((res,rej)=>{const n=++id;pending.set(n,{res,rej});ws.send(JSON.stringify({id:n,method,params}))})},close(){ws.close()}});ws.onerror=reject;ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.rej(Error(m.error.message)):p.res(m.result)}}})}
async function evalJs(c,expression){const r=await c.call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
try{
 const t=await target(),c=await connect(t.webSocketDebuggerUrl);await c.call('Runtime.enable');await c.call('Page.enable');const frame=(await c.call('Page.getFrameTree')).frameTree.frame.id;await c.call('Page.setDocumentContent',{frameId:frame,html:fixture});await c.call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:3,mobile:false});
 const pixel='data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==';
 const cards=Array.from({length:6},(_,i)=>`<article class="media"><img data-media-id="g${i}" src="${pixel}"><div class="media-tools"><button data-delete-media="g${i}">Delete</button></div></article>`).join('');
 const rows=Array.from({length:6},(_,i)=>({id:`g${i}`,trip_id:'t1',album:'evidence',storage_path:`x/photo-${i}.jpg`,thumbnail_path:null,file_name:`photo-${i}.jpg`,mime_type:'image/jpeg',created_by:'u1',created_at:'2026-09-09T00:00:00Z',visibility_state:'visible'}));
 await evalJs(c,`document.documentElement.style.background='#fff';document.body.style.cssText='margin:0;background:#fff';const style=document.createElement('style');style.textContent=${cssLiteral};document.head.appendChild(style);document.body.innerHTML='<main class="dashboard" data-home-composition="full"><section data-panel="evidence" style="width:calc(100% - 24px);margin:0 auto"><div class="gallery"><div class="empty">No evidence yet. Suspicious.</div></div></section></main>';window.__viewerUrlCalls=0;window.__rows=${JSON.stringify(rows)};window.supabase={createClient:()=>{const makeQuery=(table)=>{const filters={};const q={select(){return q},eq(k,v){filters[k]=v;return q},maybeSingle:async()=>{if(table==='trips')return{data:{owner_id:'u1'},error:null};if(table==='media'){const row=window.__rows.find(r=>Object.entries(filters).every(([k,v])=>r[k]===v));return{data:row||null,error:null}}return{data:null,error:null}},then(resolve,reject){let data=[];if(table==='media')data=window.__rows.filter(r=>Object.entries(filters).every(([k,v])=>r[k]===v));if(table==='trips')data=[{owner_id:'u1'}];return Promise.resolve({data,error:null}).then(resolve,reject)}};return q};return{from:makeQuery,auth:{getUser:async()=>({data:{user:{id:'u1'}}})},storage:{from:()=>({createSignedUrl:async()=>{window.__viewerUrlCalls++;return{data:{signedUrl:'${pixel}'},error:null}}})}}}};`);
 const empty=await evalJs(c,`(()=>{const g=document.querySelector('.gallery'),s=getComputedStyle(g);return{display:s.display,width:g.getBoundingClientRect().width,viewport:innerWidth}})()`);
 assert.notEqual(empty.display,'grid','empty Evidence must keep the core empty-state layout');assert(empty.width<empty.viewport,'empty Evidence must not become a full-width strip');
 await evalJs(c,`document.querySelector('.gallery').innerHTML=${JSON.stringify(cards)}`);await wait(80);
 const result=await evalJs(c,`(()=>{const g=document.querySelector('.gallery'),tiles=[...g.querySelectorAll(':scope > .media')],gs=getComputedStyle(g),gr=g.getBoundingClientRect();return{count:tiles.length,cols:gs.gridTemplateColumns.trim().split(/\\s+/).length,gap:parseFloat(gs.columnGap),gridWidth:gr.width,viewport:innerWidth,legacyTiles:document.querySelectorAll('.gtg-mobile-media-tile').length,legacyPrimary:document.querySelectorAll('.gtg-mobile-media-primary').length,tiles:tiles.map(t=>{const p=t.querySelector('img[data-media-id]'),tools=t.querySelector('.media-tools'),tr=t.getBoundingClientRect(),pr=p?.getBoundingClientRect(),cs=getComputedStyle(t),ps=p?getComputedStyle(p):null;return{ratio:tr.width/tr.height,radius:cs.borderRadius,childCount:t.children.length,fill:pr&&Math.abs(pr.width-tr.width)<1&&Math.abs(pr.height-tr.height)<1,fit:ps?.objectFit,mediaId:p?.dataset.mediaId||'',toolsDisplay:tools?getComputedStyle(tools).display:''}})}})()`);
 assert.equal(result.count,6);assert.equal(result.cols,3);assert(Math.abs(result.gap-1)<.1);assert(Math.abs(result.gridWidth-result.viewport)<1.5);assert.equal(result.legacyTiles,0,'core DOM must not be rewritten with legacy tile classes');assert.equal(result.legacyPrimary,0,'core media nodes must not be rewritten with legacy primary classes');
 for(const tile of result.tiles){assert(Math.abs(tile.ratio-.75)<.015);assert.equal(tile.radius,'0px');assert.equal(tile.childCount,2,'core media-tools node must remain in the DOM');assert(tile.fill);assert.equal(tile.fit,'cover');assert(tile.mediaId);assert.equal(tile.toolsDisplay,'none','mobile Full Evidence management stays inside the immersive viewer')}
 const viewerSource=fs.readFileSync(path.join(root,'girls-direct-photo-viewer.js'),'utf8').replace("const tripId=()=>new URL(location.href).searchParams.get('trip_id')||'';","const tripId=()=> 't1';");await evalJs(c,viewerSource);await wait(120);await evalJs(c,`document.querySelector('.gallery > .media img[data-media-id="g0"]').click()`);await wait(240);
 const viewer=await evalJs(c,`(()=>{const h=document.querySelector('.gtg-immersive-media-host'),s=h?.shadowRoot,stage=s?.querySelector('.stage'),media=s?.querySelector('.media'),back=s?.querySelector('.back'),top=s?.querySelector('.top'),hr=h?.getBoundingClientRect(),sr=stage?.getBoundingClientRect(),mr=media?.getBoundingClientRect(),br=back?.getBoundingClientRect(),cs=media?getComputedStyle(media):null;return{host:!!h,shadow:!!s,width:hr?.width,height:hr?.height,stageWidth:sr?.width,stageHeight:sr?.height,mediaWidth:mr?.width,mediaHeight:mr?.height,fit:cs?.objectFit,backLeft:br?.left,backTop:br?.top,topPosition:top?getComputedStyle(top).position:'',bodyPosition:getComputedStyle(document.body).position,manage:!!s?.querySelector('.manage'),menuHidden:s?.querySelector('.menu')?.hidden??null,current:window.GTGDirectMediaViewer?.current?.()?.id||''}})()`);
 assert(viewer.host&&viewer.shadow);assert(Math.abs(viewer.width-390)<1);assert(Math.abs(viewer.height-844)<1);assert(Math.abs(viewer.stageWidth-390)<1);assert(Math.abs(viewer.stageHeight-844)<1);assert(Math.abs(viewer.mediaWidth-390)<1);assert(Math.abs(viewer.mediaHeight-844)<1);assert.equal(viewer.fit,'cover');assert.equal(viewer.topPosition,'absolute');assert(viewer.backLeft>=10&&viewer.backLeft<=14);assert(viewer.backTop>=8&&viewer.backTop<=14);assert.equal(viewer.bodyPosition,'fixed');assert(viewer.manage);assert.equal(viewer.menuHidden,true);assert.equal(viewer.current,'g0');
 await evalJs(c,`window.GTGDirectMediaViewer.next()`);await wait(320);const next=await evalJs(c,`window.GTGDirectMediaViewer.current()?.id||''`);assert.equal(next,'g1','immersive viewer must build its swipe sequence from the untouched core gallery DOM');
 await evalJs(c,`document.querySelector('.gtg-immersive-media-host').shadowRoot.querySelector('.back').click()`);await wait(40);const closed=await evalJs(c,`({host:!!document.querySelector('.gtg-immersive-media-host'),bodyPosition:document.body.style.position,children:[...document.querySelectorAll('.gallery > .media')].map(t=>t.children.length)})`);assert.equal(closed.host,false);assert.equal(closed.bodyPosition,'');assert(closed.children.every(n=>n===2),'viewer must not mutate core gallery cards');
 await evalJs(c,`document.querySelector('.dashboard').dataset.homeComposition='free'`);await wait(40);const free=await evalJs(c,`(()=>{const g=document.querySelector('.gallery'),s=getComputedStyle(g);return{width:g.getBoundingClientRect().width,viewport:innerWidth,display:s.display}})()`);assert(free.width<free.viewport,'Free must not receive the Full full-bleed grid');assert.notEqual(free.display,'grid','Free must not receive the Full three-column grid style');
 console.log('PASS Girls mobile Evidence: core DOM owns one stable 3-column Full grid and immersive viewer sequence');c.close();
}finally{proc.kill('SIGKILL');try{fs.rmSync(profile,{recursive:true,force:true})}catch{}}
