import fs from 'node:fs';
import assert from 'node:assert/strict';
const readiness=fs.readFileSync('girls-media-readiness.js','utf8');
const viewer=fs.readFileSync('girls-direct-photo-viewer.js','utf8');
const html=fs.readFileSync('create-trip.html','utf8');
const loader=fs.readFileSync('girls-performance-loader.js','utf8');
assert.match(readiness,/cache:12,concurrent:2,ahead:3,behind:3,margin:500,prime:9/,'normal connections must keep the current photo plus three each side warm');
assert.match(readiness,/cache:5,concurrent:1,ahead:1,behind:1,margin:160,prime:3/,'data-saving connections must remain conservative');
assert.match(readiness,/document\.visibilityState==='hidden'/,'hidden pages must pause queued warming');
assert.match(readiness,/saveData/);assert.match(readiness,/isVideo\(r\)\|\|!r\.storage_path/);
assert.match(readiness,/warmAroundIndex/);assert.match(readiness,/radius=null/);assert.match(readiness,/warmAroundIndex\(index,'high',3\)/);assert.match(readiness,/slice\(0,limits\(\)\.prime\)/);assert.match(readiness,/pointerdown/);
assert.match(viewer,/class="track"/,'viewer must keep a persistent track');
assert.match(viewer,/const indexes=\[active\.index-1,active\.index,active\.index\+1\]/,'viewer must keep previous/current/next slots');
assert.match(viewer,/GTGMediaReadiness/,'viewer must reuse the readiness cache');assert.match(viewer,/function warmViewerWindow\(entries,index\)/);assert.match(viewer,/index-3/);assert.match(viewer,/index\+3/);
assert.match(viewer,/video\.preload=priority==='high'\?'metadata':'none'/,'video neighbours must remain lightweight');
assert(!html.includes('/girls-media-readiness.js?v=4')&&!html.includes('/girls-direct-photo-viewer.js?v=6'),'Evidence readiness/viewer must not execute on Home startup');
const warmIndex=loader.indexOf('/girls-media-readiness.js?v=4'),viewerIndex=loader.indexOf('/girls-direct-photo-viewer.js?v=6');
assert(warmIndex>0&&viewerIndex>warmIndex&&loader.includes("if(mode==='full')await loadBundle('evidenceFull')"),'Full Evidence route must preserve readiness before viewer');
console.log('PASS Girls bounded media readiness and persistent three-slide viewer');
