const fs=require('node:fs');
const assert=require('node:assert/strict');

const source=fs.readFileSync('girls-live-dashboard-hero.js','utf8');
const appSource=fs.readFileSync('girls-app-v2.js','utf8');
const heroUx=fs.readFileSync('girls-hero-vault-ux.js','utf8');
const critical=fs.readFileSync('girls-critical-style-loader.js','utf8');
const performance=fs.readFileSync('girls-performance-loader.js','utf8');
const dateFlow=fs.readFileSync('girls-date-flow.js','utf8');
const html=fs.readFileSync('create-trip.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const heroCss=fs.readFileSync('live-dashboard-hero.css','utf8');
const lightTheme=fs.readFileSync('logged-in-light-theme.js','utf8');
const legacyHero=fs.readFileSync('girls-home-hero-background.js','utf8');

assert.doesNotMatch(source,/const URL=/,'Supabase URL must not shadow the browser URL constructor');
assert.match(source,/__GTG_LIVE_DASHBOARD_HERO__/,'the Full Home photo hydrator must be a singleton');
assert.match(source,/new globalThis\.URL\(location\.href\)/,'trip ID parsing must use the browser URL constructor explicitly');
assert.match(source,/if\(hydrateScheduled\)return/,'mutation bursts must coalesce into one pending hydration');
assert.match(source,/hydrate\(\)\.catch\(/,'scheduled async hydration must handle top-level failures');
assert.match(source,/data-full-hero-owner="girls-app-v2"/,'the live runtime must target only the core-owned Full hero');
assert.doesNotMatch(source,/buildShell|hero\.innerHTML|fullHeroOwner='live-dashboard-hero'/,'the live runtime must never rebuild or claim the Full hero DOM');
assert.match(source,/live-dashboard-hero\.css\?v=10/,'Full Home hydration must retain the authoritative light hero stylesheet');
assert.match(appSource,/function dashboardHero\(days\)/,'the core app must own a dedicated Home hero renderer');
assert.match(appSource,/data-full-hero-owner="girls-app-v2"/,'the core app must declare itself as the Full hero DOM owner');
assert.match(appSource,/if\(paid\(\)\)return `<section class="hero-card live-snapshot-hero"/,'paid Home must render the final light hero directly');
assert.match(appSource,/\$\{dashboardHero\(days\)\}<div class="stat-row">/,'dashboard composition must insert exactly one authoritative hero renderer');
assert.match(appSource,/return `<section class="hero-card"><img src="\$\{esc\(hero\(\)\)\}"/,'Free must retain its existing hero renderer');
assert.match(heroUx,/live-snapshot-hero\[data-full-hero-owner="girls-app-v2"\]/,'legacy hero controls must explicitly exclude the core-owned Full hero');
assert.match(critical,/async function ensureHomeAssets\(\)/,'critical loader must expose one authoritative Home asset readiness function');
assert.match(critical,/window\.GTGCritical=\{ensureHomeAssets\}/,'Home readiness must be reusable after non-Home startup');
assert.match(critical,/gtg-home-route-pending[\s\S]*data-home-composition="full"[\s\S]*data-panel="overview"/,'Home pending guard must be Full-only');
assert.match(performance,/async function openHome\(target=null\)/,'performance loader must own one async Full Home entry gate');
assert.match(performance,/await window\.GTGCritical\?\.ensureHomeAssets\?\.\(\)/,'Full Home must wait for authoritative Home assets before activation');
assert.match(performance,/homeTab&&isFull\(\)/,'Free Home must bypass the Full readiness gate');
assert.match(source,/girls-live-dashboard-hero\.js\?v=13|__GTG_LIVE_DASHBOARD_HERO__/,'the hydration-only Full runtime must remain current');
assert.doesNotMatch(critical,/girls-home-hero-background\.js/,'the legacy all-Home dark background runtime must not load');
assert.match(critical,/live-dashboard-hero\.css\?v=10/,'critical Home CSS must use the authoritative taller Full hero stylesheet');
assert.match(critical,/dataset\.fullHeroOwner!=='girls-app-v2'/,'the first-paint cover must wait for the core-owned Full hero');
assert.match(critical,/gtg-cover-leaving/,'the cover must use the short controlled crossfade');
assert.match(critical,/prefers-reduced-motion/,'the cover must respect reduced motion');
assert.doesNotMatch(dateFlow,/girls-live-dashboard-hero\.js/,'the legacy date flow must not load a duplicate hero runtime');
assert.match(html,/girls-critical-style-loader\.js\?v=20260909-6/,'the private shell must cache-bust the Home readiness loader');
assert.match(html,/girls-app-v2\.js\?v=5/,'the private shell must cache-bust the core renderer');
assert.match(html,/girls-hero-vault-ux\.js\?v=4/,'the private shell must cache-bust the retired legacy hero control path');
assert.match(html,/girls-performance-loader\.js\?v=8/,'the private shell must cache-bust the unified route readiness loader');
assert.match(html,/girls-pwa-register\.js\?v=4/,'the private shell must refresh PWA registration code');
assert.match(html,/class="gtg-boot-shell"/,'the private shell must use the isolated light startup skeleton');
assert.doesNotMatch(html,/gtg-boot-shell[\s\S]*girls-trip-guide-logo\.webp/,'the startup skeleton must not render the old square logo');
assert.match(sw,/gtg-pwa-v21/,'the current Full Home composition must use the latest offline cache generation');
assert.match(heroCss,/\.live-message-card\{[^}]*background:linear-gradient\(145deg,#fffafd,#fbe7f1\)/,'the message preview must use the light blush surface');
assert.match(heroCss,/\.live-photo-frame\{[^}]*background:linear-gradient\(145deg,#fffafd,#fce9f3\)/,'the empty photo preview must use the light blush surface');
assert.doesNotMatch(heroCss,/\.live-message-card\{[^}]*#21141d/,'the legacy near-black message surface must not return');
assert.match(heroCss,/linear-gradient\(145deg,#fff 0%,#fff8fb 58%,#fff4f9 100%\)/,'the Full hero main surface must be light');
assert.match(heroCss,/grid-template-areas:"title dates" "snapshot snapshot"/,'photo focus must not alter the title/date grid');
assert.match(heroCss,/@media\(max-width:390px\)[\s\S]*\.live-snapshot-bottom\{[^}]*min-height:178px/,'390px Full hero message/photo row must be about 25% taller');
assert.match(lightTheme,/hero-card:not\(\.live-snapshot-hero\)/,'legacy hero theme rules must exclude the Full hero');
assert.doesNotMatch(legacyHero,/background:/,'the retired legacy Home hero runtime must not own a background');

console.log('Girls live dashboard hero safety: PASS');
