import fs from 'node:fs';
import assert from 'node:assert/strict';
const readiness=fs.readFileSync('girls-media-readiness.js','utf8');
const viewer=fs.readFileSync('girls-direct-photo-viewer.js','utf8');
const html=fs.readFileSync('create-trip.html','utf8');
assert.match(readiness,/CACHE_LIMIT=9/,'warm cache must stay bounded');
assert.match(readiness,/MAX_CONCURRENT=2/,'full originals must be warmed with bounded concurrency');
assert.match(readiness,/NEXT_ROW=3/,'only the next three-tile row should be speculatively warmed');
assert.match(readiness,/speculativeNetworkOK/,'data-saver and slow-network guard required');
assert.match(readiness,/isVideo\(r\)\|\|!r\.storage_path/,'videos must not be speculatively fully downloaded');
assert.match(readiness,/fetchPriority=.*high/,'touch intent must be able to raise media priority');
assert.match(readiness,/pointerdown/,'touch/pointer intent must start high-priority warming before click');
assert.match(readiness,/rootMargin:'180px 0px'/,'readiness window should stay close to the visible gallery');
assert.match(viewer,/previewUrl/,'viewer must accept the already-rendered thumbnail');
assert.match(viewer,/stage\.replaceChildren\(previewMedia\)/,'thumbnail must paint immediately into the immersive stage');
assert.match(viewer,/GTGMediaReadiness/,'viewer must reuse or promote the warm original');
assert.match(viewer,/video\.poster=previewUrl/,'video must remain poster-first');
assert.match(viewer,/preload='metadata'/,'video must not be fully prefetched before interaction');
const warmIndex=html.indexOf('/girls-media-readiness.js?v=1'),viewerIndex=html.indexOf('/girls-direct-photo-viewer.js?v=4');
assert(warmIndex>0&&viewerIndex>warmIndex,'readiness runtime must load before the immersive viewer');
console.log('PASS Girls media readiness: bounded next-row photo warming, pointer priority, instant thumbnail paint and poster-first video');
