import fs from 'node:fs';
import assert from 'node:assert/strict';
const readiness=fs.readFileSync('girls-media-readiness.js','utf8');
const viewer=fs.readFileSync('girls-direct-photo-viewer.js','utf8');
const html=fs.readFileSync('create-trip.html','utf8');
assert.match(readiness,/cache:18,concurrent:4,ahead:6,behind:3,margin:1100,prime:12/,'fast connections should use a larger bounded readiness window');
assert.match(readiness,/cache:9,concurrent:2,ahead:3,behind:0,margin:260,prime:6/,'constrained connections must retain conservative warming');
assert.match(readiness,/saveData/,'data-saver guard required');
assert.match(readiness,/slow-2g\|2g/,'very slow networks must stay conservative');
assert.match(readiness,/isVideo\(r\)\|\|!r\.storage_path/,'videos must not be speculatively fully downloaded');
assert.match(readiness,/fetchPriority=.*high/,'touch intent must be able to raise media priority');
assert.match(readiness,/warmAroundIndex/,'adjacent media should be proactively prepared');
assert.match(readiness,/pointerdown/,'pointer intent must promote current and adjacent media before click');
assert.match(readiness,/rootMargin:`\$\{limits\(\)\.margin\}px 0px`/,'readiness distance must adapt to network capacity');
assert.match(viewer,/previewUrl/,'viewer must accept the already-rendered thumbnail');
assert.match(viewer,/stage\.replaceChildren\(previewMedia\)/,'thumbnail must paint immediately into the immersive stage');
assert.match(viewer,/GTGMediaReadiness/,'viewer must reuse or promote the warm original');
assert.match(viewer,/video\.poster=previewUrl/,'video must remain poster-first');
assert.match(viewer,/preload='metadata'/,'video must not be fully prefetched before interaction');
const warmIndex=html.indexOf('/girls-media-readiness.js?v=2'),viewerIndex=html.indexOf('/girls-direct-photo-viewer.js?v=4');
assert(warmIndex>0&&viewerIndex>warmIndex,'adaptive readiness runtime must load before the immersive viewer');
console.log('PASS Girls media readiness: adaptive fast-network lookahead, conservative slow-network guard, instant thumbnail paint and poster-first video');
