const fs=require('node:fs');
const assert=require('node:assert/strict');

const source=fs.readFileSync('girls-live-dashboard-hero.js','utf8');
const critical=fs.readFileSync('girls-critical-style-loader.js','utf8');
const dateFlow=fs.readFileSync('girls-date-flow.js','utf8');
const html=fs.readFileSync('create-trip.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const heroCss=fs.readFileSync('live-dashboard-hero.css','utf8');
const lightTheme=fs.readFileSync('logged-in-light-theme.js','utf8');
const legacyHero=fs.readFileSync('girls-home-hero-background.js','utf8');

assert.doesNotMatch(source,/const URL=/,'Supabase URL must not shadow the browser URL constructor');
assert.match(source,/__GTG_LIVE_DASHBOARD_HERO__/,'the dashboard hero runtime must be a singleton');
assert.match(source,/new globalThis\.URL\(location\.href\)/,'trip ID parsing must use the browser URL constructor explicitly');
assert.match(source,/if\(mountScheduled\)return/,'mutation bursts must coalesce into one pending mount');
assert.match(source,/mount\(\)\.catch\(/,'scheduled async mounts must handle top-level failures');
assert.match(source,/fullHeroOwner='live-dashboard-hero'/,'Full hero runtime must declare itself as the visual owner');
assert.match(source,/live-dashboard-hero\.css\?v=10/,'Full hero runtime must use the authoritative taller light hero stylesheet');
assert.match(source,/live-snapshot-bottom is-message-focused/,'Full hero must isolate the interactive message/photo row');
assert.match(critical,/girls-live-dashboard-hero\.js\?v=12/,'the critical loader must cache-bust the taller Full hero runtime');
assert.doesNotMatch(critical,/girls-home-hero-background\.js/,'the legacy all-Home dark background runtime must not load');
assert.match(critical,/live-dashboard-hero\.css\?v=10/,'critical Home CSS must use the authoritative taller Full hero stylesheet');
assert.match(critical,/dataset\.fullHeroOwner!=='live-dashboard-hero'/,'the first-paint cover must wait for the authoritative Full hero owner');
assert.match(critical,/gtg-cover-leaving/,'the cover must use the short controlled crossfade');
assert.match(critical,/prefers-reduced-motion/,'the cover must respect reduced motion');
assert.doesNotMatch(dateFlow,/girls-live-dashboard-hero\.js/,'the legacy date flow must not load a duplicate hero runtime');
assert.match(html,/girls-critical-style-loader\.js\?v=20260909-4/,'the private shell must cache-bust the taller Full hero critical loader');
assert.match(html,/girls-performance-loader\.js\?v=5/,'the private shell must refresh the isolated Evidence loader');
assert.match(html,/girls-pwa-register\.js\?v=4/,'the private shell must refresh PWA registration code');
assert.match(html,/class="gtg-boot-shell"/,'the private shell must use the isolated light startup skeleton');
assert.doesNotMatch(html,/gtg-boot-shell[\s\S]*girls-trip-guide-logo\.webp/,'the startup skeleton must not render the old square logo');
assert.match(sw,/gtg-pwa-v15/,'the taller Full hero must advance the offline cache generation');
assert.match(heroCss,/\.live-message-card\{[^}]*background:linear-gradient\(145deg,#fffafd,#fbe7f1\)/,'the message preview must use the light blush surface');
assert.match(heroCss,/\.live-photo-frame\{[^}]*background:linear-gradient\(145deg,#fffafd,#fce9f3\)/,'the empty photo preview must use the light blush surface');
assert.doesNotMatch(heroCss,/\.live-message-card\{[^}]*#21141d/,'the legacy near-black message surface must not return');
assert.match(heroCss,/linear-gradient\(145deg,#fff 0%,#fff8fb 58%,#fff4f9 100%\)/,'the Full hero main surface must be light');
assert.match(heroCss,/grid-template-areas:"title dates" "snapshot snapshot"/,'photo focus must not alter the title/date grid');
assert.match(heroCss,/@media\(max-width:390px\)[\s\S]*\.live-snapshot-bottom\{[^}]*min-height:178px/,'390px Full hero message/photo row must be about 25% taller');
assert.match(lightTheme,/hero-card:not\(\.live-snapshot-hero\)/,'legacy hero theme rules must exclude the Full hero');
assert.doesNotMatch(legacyHero,/background:/,'the retired legacy Home hero runtime must not own a background');

console.log('Girls live dashboard hero safety: PASS');
